/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_hostname(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_motor_current(void);
void HTTPPrint_motor_railvoltage(void);
void HTTPPrint_motor_direction(void);
void HTTPPrint_config_mac(void);
void HTTPPrint_version(void);
void HTTPPrint_builddate(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000000:
			HTTPPrint_hostname();
			break;
        case 0x00000001:
			HTTPPrint_config_ip();
			break;
        case 0x00000002:
			HTTPPrint_motor_current();
			break;
        case 0x00000003:
			HTTPPrint_motor_railvoltage();
			break;
        case 0x00000004:
			HTTPPrint_motor_direction();
			break;
        case 0x00000005:
			HTTPPrint_config_mac();
			break;
        case 0x00000006:
			HTTPPrint_version();
			break;
        case 0x00000007:
			HTTPPrint_builddate();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
