<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>BDCMC - MIL</title>
<link href="/mil.css" rel="stylesheet" type="text/css" />
<script src="/mil.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">


<div style="padding:0 0 5px 5px">
	<img src="/mil_logo.gif" alt="MIL logo" align="left" />
	<h1 align="center">DC Motor Control Panel</h1>
</div>


<!--This gives the pretty bar below the title stuff-->
<div id="title"> </div>

<div id="menu">
<a href="/index.htm">Home</a>
<a href="/netconfig.htm">Network Configuration</a>
<a href="/mtrconfig.htm">Motor Configuration</a>
</div>